export const MOCK_RECIPES = [
    {
        id: "1",
        title: "Classic Avocado Toast",
        description: "A simple yet delicious breakfast staple with a touch of chili flakes and lemon.",
        image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=2080&auto=format&fit=crop",
        category: "Breakfast",
        ingredients: "2 slices of sourdough bread\n1 ripe avocado\nRed chili flakes\nLemon juice\nSea salt",
        instructions: "1. Toast the bread until golden brown.\n2. Mash the avocado in a small bowl with lemon juice and salt.\n3. Spread the avocado on the toast.\n4. Sprinkle with chili flakes and enjoy!",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 124,
        has_liked: false,
        is_saved: true,
    },
    {
        id: "2",
        title: "Creamy Garlic Pasta",
        description: "Rich, buttery pasta with roasted garlic and freshly grated parmesan cheese.",
        image_url: "https://plus.unsplash.com/premium_photo-1664472634106-1430c3973e68",
        category: "Dinner",
        ingredients: "200g Fettuccine\n4 cloves garlic\n100ml heavy cream\n50g Parmesan\nFresh parsley",
        instructions: "1. Boil pasta according to package instructions.\n2. Sauté minced garlic in butter until fragrant.\n3. Add cream and simmer until thickened.\n4. Toss pasta with sauce and top with parmesan.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 89,
        has_liked: true,
        is_saved: false,
    },
    {
        id: "3",
        title: "Vegan Buddha Bowl",
        description: "A colorful and nutritious bowl packed with quinoa, chickpeas, and fresh greens.",
        image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=2070&auto=format&fit=crop",
        category: "Lunch",
        ingredients: "1 cup Quinoa\n1 can Chickpeas\nKale\nSweet potato\nTahini dressing",
        instructions: "1. Roast sweet potatoes and chickpeas at 400°F.\n2. Cook quinoa according to package instructions.\n3. Assemble bowl with kale, quinoa, and roasted veggies.\n4. Drizzle with tahini dressing.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 56,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "4",
        title: "Berry Blast Smoothie",
        description: "Refreshing mix of blueberries, strawberries, and almond milk.",
        image_url: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=2070&auto=format&fit=crop",
        category: "Breakfast",
        ingredients: "1 cup Mixed berries\n1 banana\n1 cup Almond milk\n1 tbsp Honey",
        instructions: "1. Place all ingredients in a blender.\n2. Blend until smooth.\n3. Pour into a glass and serve chilled.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 42,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "5",
        title: "Honey Glazed Salmon",
        description: "Pan-seared salmon with a sweet and savory honey garlic glaze.",
        image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=2070&auto=format&fit=crop",
        category: "Dinner",
        ingredients: "Salmon fillet\nHoney\nSoy sauce\nLemon juice\nGarlic",
        instructions: "1. Whisk honey, soy sauce, lemon, and garlic.\n2. Sear salmon in a hot pan for 4 mins per side.\n3. Pour glaze over and simmer until thickened.\n4. Serve with roasted asparagus.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 342,
        has_liked: true,
        is_saved: false,
    },
    {
        id: "6",
        title: "Smoked Salmon Bagel",
        description: "Classic breakfast favorite with herb cream cheese, capers, and red onion.",
        image_url: "https://images.unsplash.com/photo-1519623286359-e9f3cbef015b?q=80&w=2070&auto=format&fit=crop",
        category: "Breakfast",
        ingredients: "Everything bagel\nSmoked salmon\nCream cheese\nCapers\nRed onion",
        instructions: "1. Toast the bagel until golden brown.\n2. Spread a generous layer of cream cheese.\n3. Layer smoked salmon, onions, and capers.\n4. Season with black pepper.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 215,
        has_liked: false,
        is_saved: true,
    },
    {
        id: "7",
        title: "Truffle Mushroom Risotto",
        description: "Elegant Italian rice dish with earthy mushrooms and truffle oil.",
        image_url: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?q=80&w=2070&auto=format&fit=crop",
        category: "Dinner",
        ingredients: "Arborio rice\nCremini mushrooms\nVegetable stock\nWhite wine\nTruffle oil",
        instructions: "1. Sauté mushrooms until brown.\n2. Toast rice in the same pan.\n3. Add stock one ladle at a time, stirring constantly.\n4. Finish with butter, parmesan, and truffle oil.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 567,
        has_liked: true,
        is_saved: true,
    },
    {
        id: "8",
        title: "Classic Margherita Pizza",
        description: "Neapolitan-style pizza with san marzano tomatoes and fresh mozzarella.",
        image_url: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?q=80&w=2070&auto=format&fit=crop",
        category: "Lunch",
        ingredients: "Pizza dough\nTomato sauce\nFresh mozzarella\nBasil leaves\nOlive oil",
        instructions: "1. Stretch dough into a thin circle.\n2. Spread sauce and add mozzarella chunks.\n3. Bake at 500°F until crust is charred.\n4. Top with fresh basil and olive oil.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 890,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "9",
        title: "Dark Chocolate Fondant",
        description: "Decadent lava cake with a warm, gooey chocolate center.",
        image_url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=2070&auto=format&fit=crop",
        category: "Dessert",
        ingredients: "Dark chocolate\nButter\nEggs\nSugar\nFlour",
        instructions: "1. Melt chocolate and butter together.\n2. Whisk eggs and sugar until pale.\n3. Fold in chocolate and flour.\n4. Bake in ramekins at 400°F for exactly 12 mins.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 421,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "10",
        title: "Crispy Tofu Salad",
        description: "Asian-inspired salad with golden tofu and sesame ginger dressing.",
        image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=2070&auto=format&fit=crop",
        category: "Vegan",
        ingredients: "Firm tofu\nMixed greens\nEdamame\nSesame seeds\nGinger dressing",
        instructions: "1. Press and cube tofu.\n2. Toss in cornstarch and fry until crispy.\n3. Build salad with greens and edamame.\n4. Add tofu and drizzle with dressing.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 176,
        has_liked: true,
        is_saved: false,
    },
    {
        id: "11",
        title: "Blueberry Lemon Pancakes",
        description: "Fluffy buttermilk pancakes bursting with fresh blueberries.",
        image_url: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?q=80&w=2070&auto=format&fit=crop",
        category: "Breakfast",
        ingredients: "Flour\nButtermilk\nBlueberries\nLemon zest\nMaple syrup",
        instructions: "1. Mix dry and wet ingredients separately.\n2. Combine and fold in berries and zest.\n3. Cook on a hot griddle until bubbles form.\n4. Stack high and serve with syrup.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 289,
        has_liked: false,
        is_saved: true,
    },
    {
        id: "12",
        title: "Grilled Ribeye Steak",
        description: "Perfectly seasoned steak with herb butter and garlic mash.",
        image_url: "https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=2070&auto=format&fit=crop",
        category: "Dinner",
        ingredients: "Ribeye steak\nRosemary\nThyme\nButter\nPotatoes",
        instructions: "1. Season steak generously with salt and pepper.\n2. Sear in a hot cast iron pan for 3-4 mins per side.\n3. Baste with butter and herbs.\n4. Rest for 10 mins before slicing.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 1045,
        has_liked: true,
        is_saved: false,
    },
    {
        id: "13",
        title: "Greek Mezze Platter",
        description: "Traditional Mediterranean spread with hummus, olives, and warm pita.",
        image_url: "https://images.unsplash.com/photo-1544124499-58912cbddaad?q=80&w=2070&auto=format&fit=crop",
        category: "Lunch",
        ingredients: "Hummus\nTzatziki\nKalamata olives\nFeta cheese\nPita bread",
        instructions: "1. Arrange hummus and tzatziki in small bowls.\n2. Scatter olives and cubed feta around the platter.\n3. Warm the pita bread and cut into triangles.\n4. Garnish with fresh parsley and olive oil.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 312,
        has_liked: false,
        is_saved: true,
    },
    {
        id: "14",
        title: "Matcha Green Tea Latte",
        description: "Smooth and earthy ceremonial grade matcha with frothed oat milk.",
        image_url: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?q=80&w=2070&auto=format&fit=crop",
        category: "Drink",
        ingredients: "Matcha powder\nHot water\nOat milk\nMaple syrup",
        instructions: "1. Sift matcha into a bowl.\n2. Add hot water and whisk until frothy.\n3. Heat and froth the oat milk.\n4. Combine matcha and milk, sweeten to taste.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 156,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "15",
        title: "Spicy Tuna Sushi Roll",
        description: "Hand-rolled sushi with fresh ahi tuna and spicy sriracha mayo.",
        image_url: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=2070&auto=format&fit=crop",
        category: "Lunch",
        ingredients: "Sushi rice\nNori sheets\nAhi tuna\nSriracha\nCucumber",
        instructions: "1. Mix minced tuna with sriracha and mayo.\n2. Spread rice over nori sheet.\n3. Add tuna and cucumber strips.\n4. Roll tightly and slice into 8 pieces.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 743,
        has_liked: true,
        is_saved: false,
    },
    {
        id: "16",
        title: "Thai Green Curry",
        description: "Fragrant coconut curry with bamboo shoots, basil, and lime leaves.",
        image_url: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?q=80&w=2070&auto=format&fit=crop",
        category: "Dinner",
        ingredients: "Coconut milk\nGreen curry paste\nChicken or Tofu\nEggplant\nThai basil",
        instructions: "1. Fry curry paste in coconut cream until fragrant.\n2. Add protein and vegetables.\n3. Pour in remaining coconut milk and simmer.\n4. Stir in fish sauce, sugar, and fresh basil.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 521,
        has_liked: false,
        is_saved: true,
    },
    {
        id: "17",
        title: "French Onion Soup",
        description: "Classic rich beef broth with caramelized onions and gruyère crust.",
        image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=2070&auto=format&fit=crop",
        category: "Lunch",
        ingredients: "Yellow onions\nBeef stock\nThyme\nBaguette slices\nGruyère cheese",
        instructions: "1. Caramelize onions slowly for 45 mins.\n2. Add stock and herbs, simmer for 30 mins.\n3. Ladle into bowls, top with bread and cheese.\n4. Broil until cheese is bubbly and brown.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 389,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "18",
        title: "Strawberry Cheesecake",
        description: "New York style cheesecake with a buttery graham cracker crust.",
        image_url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=2070&auto=format&fit=crop",
        category: "Dessert",
        ingredients: "Cream cheese\nGraham crackers\nSugar\nSour cream\nFresh strawberries",
        instructions: "1. Press cracker crust into pan.\n2. Beat cream cheese and sugar until smooth.\n3. Pour over crust and bake in water bath.\n4. Chill for 6 hours and top with berry glaze.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 1205,
        has_liked: true,
        is_saved: true,
    },
    {
        id: "19",
        title: "Quinoa Tabbouleh",
        description: "Fresh Middle Eastern salad with parsley, mint, and lemon juice.",
        image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=2070&auto=format&fit=crop",
        category: "Vegan",
        ingredients: "Cooked quinoa\nFlat leaf parsley\nFresh mint\nTomatoes\nLemon vinaigrette",
        instructions: "1. Finely chop parsley and mint.\n2. Toss with quinoa and diced tomatoes.\n3. Pour over lemon and olive oil dressing.\n4. Chill for 30 mins before serving.",
        user_id: "demo-user",
        created_at: new Date().toISOString(),
        like_count: 245,
        has_liked: false,
        is_saved: false,
    },
    {
        id: "20",
        title: "Pulled Pork Sliders",
        description: "Slow-cooked BBQ pork with tangy coleslaw on brioche buns.",
        image_url: "https://plus.unsplash.com/premium_photo-1740162510836-01dbc58be28d",
        category: "Lunch",
        ingredients: "Pork shoulder\nBBQ sauce\nColeslaw mix\nBrioche buns\nPickles",
        instructions: "1. Slow cook pork for 8 hours until tender.\n2. Shred and toss with BBQ sauce.\n3. Toast buns and layer with pork and slaw.\n4. Serve with extra pickles on the side.",
        user_id: "other-user",
        created_at: new Date().toISOString(),
        like_count: 862,
        has_liked: false,
        is_saved: false,
    },
];
